
CREATE SEQUENCE auto_id_seq;

CREATE TABLE GuidTable (
	Id UUID NOT NULL PRIMARY KEY
);

CREATE TABLE StringTable(
	Str VARCHAR(10) NOT NULL PRIMARY KEY
);

CREATE TABLE DateTimeTable (
	dtId UUID NOT NULL PRIMARY KEY,
	dtDt TIMESTAMP NOT NULL
);

CREATE TABLE NDateTimeTable (
	dtId UUID NOT NULL PRIMARY KEY,
	dtDt TIMESTAMP NULL
);

CREATE TABLE DateTimeTable2 (
	dtId UUID NOT NULL PRIMARY KEY,
	dtDt TIMESTAMP NOT NULL
);

CREATE TABLE NDateTimeTable2 (
	dtId UUID NOT NULL PRIMARY KEY,
	dtDt TIMESTAMP NULL
);

CREATE TABLE DateTimeTableOffset (
	dtId UUID NOT NULL PRIMARY KEY,
	dtDt TIMESTAMP WITH TIME ZONE NOT NULL,
	dtNullDt TIMESTAMP WITH TIME ZONE NULL
);


CREATE TABLE EnumTable (
	EnumValue SMALLINT NOT NULL
);

CREATE TABLE AutoTable (
	Id INTEGER NOT NULL DEFAULT NEXTVAL('auto_id_seq') PRIMARY KEY,
	Text VARCHAR(255) NOT NULL
);

CREATE TABLE BooleanTable (
	Id UUID NOT NULL PRIMARY KEY,
	Bool BOOLEAN NOT NULL
);

CREATE TABLE DecimalTable (
	Id INTEGER NOT NULL DEFAULT NEXTVAL('auto_id_seq') PRIMARY KEY,
	DecimalValue DECIMAL(19,8) NOT NULL
);

CREATE TABLE NDecimalTable (
	Id INTEGER NOT NULL DEFAULT NEXTVAL('auto_id_seq') PRIMARY KEY,
	DecimalValue DECIMAL(19,8) NULL
);

CREATE TABLE IntTable (
	Id UUID NOT NULL PRIMARY KEY,
	IntValue INTEGER NOT NULL	
);

CREATE TABLE NIntTable (
	Id UUID NOT NULL PRIMARY KEY,
	IntValue INTEGER NULL
);

CREATE TABLE BigIntTable (
	Id INT8 NOT NULL DEFAULT NEXTVAL('auto_id_seq') PRIMARY KEY,
	IntValue INT8 NULL
);

CREATE TABLE SmallIntTable (
	Id INT2 NOT NULL DEFAULT NEXTVAL('auto_id_seq') PRIMARY KEY,
	IntValue INT2 NULL
);

CREATE TABLE BinaryTable (
	BinaryValue BYTEA NOT NULL,
	NBinaryValue BYTEA NULL
);

CREATE TABLE Earthquake (
	earCUSP_ID INTEGER NOT NULL,
	earLAT DECIMAL(19,8) NOT NULL,
	earLONG DECIMAL(19,8) NOT NULL,
	earNZMGE INTEGER NOT NULL,
	earNZMGN INTEGER NOT NULL,
	earDateTime TIMESTAMP NOT NULL,
	earMAG DECIMAL(19,8) NOT NULL,
	earDEPTH DECIMAL(19,8) NOT NULL,	
	CONSTRAINT pk_Earthquake PRIMARY KEY(earCUSP_ID)
);

CREATE TABLE FloatTable (
	Id UUID NOT NULL PRIMARY KEY,
	Value REAL NOT NULL,
	NValue REAL NULL
);

CREATE TABLE DoubleTable (
	Id UUID NOT NULL PRIMARY KEY,
	Value FLOAT NOT NULL,
	NValue FLOAT NULL
);

CREATE TABLE Person (
	perKey UUID NOT NULL PRIMARY KEY,
	perFirstName VARCHAR(100) NOT NULL,
	perSurname VARCHAR(100) NOT NULL
);

CREATE TABLE OrderLog (
	ordKey UUID NOT NULL PRIMARY KEY,
	ordPersonKey UUID NOT NULL,
	ordItem VARCHAR(100) NOT NULL,
	CONSTRAINT fk_Order_Person FOREIGN KEY(ordPersonKey) REFERENCES Person(perKey)
);

CREATE TABLE PersonId (
	perId INTEGER NOT NULL DEFAULT NEXTVAL('auto_id_seq') PRIMARY KEY,
	perFirstName VARCHAR(100) NOT NULL,
	perSurname VARCHAR(100) NOT NULL
);

CREATE TABLE OrderLogId (
	ordId INTEGER NOT NULL DEFAULT NEXTVAL('auto_id_seq') PRIMARY KEY,
	ordPersonId INTEGER NOT NULL,
	ordItem VARCHAR(100) NOT NULL,
	CONSTRAINT fk_OrderId_PersonId FOREIGN KEY(ordPersonId) REFERENCES PersonId(perId)
);


--CREATE SCHEMA IF NOT EXISTS test_schema;

--CREATE SEQUENCE test_schema.auto_id_seq;

--CREATE TABLE test_schema.SchemaTable (
--	schId INTEGER NOT NULL DEFAULT NEXTVAL('test_schema.auto_id_seq') PRIMARY KEY,
--	schText NVARCHAR(1000) NOT NULL
--);